# Generated by Django 4.1 on 2022-09-26 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_newslikes'),
    ]

    operations = [
        migrations.AddField(
            model_name='newslikes',
            name='create_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
