# Generated by Django 4.0.8 on 2022-10-16 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileIcon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Наименование иконки')),
                ('suffix', models.CharField(blank=True, max_length=100, verbose_name='Тип файла')),
                ('icon_url', models.CharField(blank=True, max_length=100, verbose_name='Ссылка на иконку')),
            ],
            options={
                'verbose_name': 'Иконки файлов',
                'verbose_name_plural': 'Иконки файлов',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='ModuleName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(max_length=100, verbose_name='Техническое название модуля')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Наименование модуля')),
            ],
            options={
                'verbose_name': 'Файловое хранилище для модулей',
                'verbose_name_plural': 'Файловое хранилище для модулей',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='CommonFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_record', models.IntegerField(default=0, verbose_name='ID записи')),
                ('name', models.CharField(blank=True, max_length=500, verbose_name='Название файла')),
                ('size', models.FloatField(default=0, verbose_name='Размер файла')),
                ('type', models.CharField(blank=True, max_length=20, verbose_name='Тип файла')),
                ('attached_file', models.FileField(blank=True, upload_to='files/%Y/%m/%d', verbose_name='Файлы')),
                ('icon', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='icon_common_files', to='common.fileicon', verbose_name='Иконка')),
                ('module_name', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='module_common_files', to='common.modulename', verbose_name='Модуль')),
            ],
            options={
                'verbose_name': 'Файлы',
                'verbose_name_plural': 'Файлы',
                'ordering': ['pk'],
            },
        ),
    ]
