# Generated by Django 4.0.8 on 2022-10-16 14:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_commonfiles_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonfiles',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата загрузки'),
            preserve_default=False,
        ),
    ]
