# Generated by Django 4.0.8 on 2022-10-16 14:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0003_commonfiles_uploaded_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_record', models.IntegerField(default=0, verbose_name='ID записи')),
                ('description', models.TextField(max_length=300, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('status', models.BooleanField(default=True, verbose_name='Видимость')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='comment_author', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('module_name', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='module_common_comment', to='common.modulename', verbose_name='Модуль')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='common.comments')),
            ],
            options={
                'verbose_name': 'Комментарии',
                'verbose_name_plural': 'Комметарии',
                'ordering': ['-created_at'],
            },
        ),
    ]
