# Generated by Django 4.0.8 on 2022-10-17 08:04

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_alter_comments_options_comments_level_comments_lft_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='common.comments'),
        ),
    ]
