# Generated by Django 4.1 on 2022-10-05 11:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PriorityToDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=20, verbose_name='Приоритет')),
                ('color', models.CharField(max_length=20, verbose_name='Цвет Bootstrap')),
                ('color_html', models.CharField(max_length=7, verbose_name='Цвет HTML')),
            ],
            options={
                'verbose_name': 'Приоритет',
                'verbose_name_plural': 'Приоритеты',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Статус')),
                ('color', models.CharField(max_length=30, verbose_name='Цвет статуса')),
            ],
            options={
                'verbose_name': 'Статус',
                'verbose_name_plural': 'Статус',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Последнее обновление')),
                ('bdate', models.DateField(blank=True, verbose_name='Дата начала')),
                ('edate', models.DateField(blank=True, verbose_name='Дата завершения')),
                ('completed', models.BooleanField(default=False, verbose_name='Исполнено')),
                ('reminder', models.BooleanField(default=False, verbose_name='Выделить')),
                ('progress', models.IntegerField(default=0, verbose_name='Прогресс')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('priority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.prioritytodo', verbose_name='Приоритет')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.status', verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Заметки',
                'verbose_name_plural': 'Заметки',
                'ordering': ['-created_at'],
            },
        ),
    ]
