# Generated by Django 4.1 on 2022-10-05 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attached_file', models.FileField(blank=True, upload_to='files/%Y/%m/%d', verbose_name='Файлы')),
                ('todo_relate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.todo', verbose_name='Задача')),
            ],
            options={
                'verbose_name': 'Файлы',
                'verbose_name_plural': 'Файлы',
                'ordering': ['pk'],
            },
        ),
    ]
