# Generated by Django 4.1 on 2022-10-05 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='attached_file',
            field=models.ImageField(blank=True, upload_to='files/%Y/%m/%d', verbose_name='Файлы'),
        ),
    ]
