# Generated by Django 4.1 on 2022-10-05 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_alter_files_attached_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='attached_file',
            field=models.FileField(blank=True, upload_to='files/%Y/%m/%d', verbose_name='Файлы'),
        ),
    ]
