# Generated by Django 4.1 on 2022-10-05 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_alter_files_attached_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='name',
            field=models.CharField(blank=True, max_length=500, verbose_name='Название файла'),
        ),
        migrations.AddField(
            model_name='files',
            name='size',
            field=models.FloatField(default=0, verbose_name='Размер файла'),
        ),
        migrations.AddField(
            model_name='files',
            name='type',
            field=models.CharField(blank=True, max_length=20, verbose_name='Тип файла'),
        ),
    ]
