# Generated by Django 4.1 on 2022-10-06 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_files_name_files_size_files_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileIcon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Наименование иконки')),
                ('suffix', models.CharField(blank=True, max_length=100, verbose_name='Тип файла')),
                ('icon_url', models.CharField(blank=True, max_length=100, verbose_name='Ссылка на иконку')),
            ],
            options={
                'verbose_name': 'Иконки файлов',
                'verbose_name_plural': 'Иконки файлов',
                'ordering': ['-pk'],
            },
        ),
    ]
