# Generated by Django 4.1 on 2022-10-06 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_fileicon_files_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='icon',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='todo.fileicon', verbose_name='Иконка'),
            preserve_default=False,
        ),
    ]
