# Generated by Django 4.0.8 on 2022-10-07 10:08

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_files_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Описание'),
        ),
    ]
