# Generated by Django 4.0.8 on 2022-10-28 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoAlbume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Наименование')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата обноваления')),
                ('event_at', models.DateTimeField(blank=True, null=True, verbose_name='Дтаа события')),
                ('event_description', models.TextField(blank=True, null=True, verbose_name='Описание события')),
            ],
            options={
                'verbose_name': 'Фотоальбом',
                'verbose_name_plural': 'Фотоальбом',
                'ordering': ['-pk'],
            },
        ),
    ]
