# Generated by Django 4.0.8 on 2022-10-29 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoalbum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photoalbume',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='photoalbum/%Y/%m/%d', verbose_name='Изображение обложки'),
        ),
        migrations.AlterField(
            model_name='photoalbume',
            name='event_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата события'),
        ),
    ]
