# Generated by Django 4.0.8 on 2022-10-29 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_company'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('photoalbum', '0002_photoalbume_image_alter_photoalbume_event_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='photoalbume',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='photoalbume_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='photoalbume',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_id', to='common.company'),
        ),
    ]
