# Generated by Django 4.0.8 on 2022-10-29 15:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0007_company'),
        ('photoalbum', '0004_alter_photoalbume_event_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoAlbumeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Наименование')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата обноваления')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='photoalbume_category_author', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.company')),
            ],
            options={
                'verbose_name': 'Категория фотоальбома',
                'verbose_name_plural': 'Категория фотоальбома',
                'ordering': ['-pk'],
            },
        ),
    ]
