# Generated by Django 4.0.8 on 2022-10-29 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photoalbum', '0005_photoalbumecategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='photoalbume',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='photoalbume_category', to='photoalbum.photoalbumecategory'),
        ),
    ]
