# Generated by Django 4.1 on 2022-09-29 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlerstList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_name', models.CharField(max_length=100, verbose_name='Название URL')),
                ('color', models.CharField(blank=True, max_length=100, verbose_name='Цвет уведомления')),
                ('description', models.CharField(blank=True, max_length=1000, verbose_name='Описание уведомления')),
            ],
            options={
                'verbose_name': 'Уведомления',
                'verbose_name_plural': 'Уведомления',
                'ordering': ['-pk'],
            },
        ),
    ]
