# Generated by Django 4.0.8 on 2022-10-07 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proj_man', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='project',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.PROTECT, related_name='project', to='proj_man.project', verbose_name='Проект'),
            preserve_default=False,
        ),
    ]
