# Generated by Django 4.0.8 on 2022-10-07 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj_man', '0003_alter_tasks_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='level',
            field=models.PositiveIntegerField(default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tasks',
            name='lft',
            field=models.PositiveIntegerField(default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tasks',
            name='rght',
            field=models.PositiveIntegerField(default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tasks',
            name='tree_id',
            field=models.PositiveIntegerField(db_index=True, default=1, editable=False),
            preserve_default=False,
        ),
    ]
