# Generated by Django 4.0.8 on 2022-10-08 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj_man', '0005_alter_tasks_bdate_alter_tasks_co_executor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='progress',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Прогресс'),
        ),
    ]
