# Generated by Django 4.0.8 on 2022-10-09 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proj_man', '0007_alter_tasks_author_alter_tasks_executor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='project', to='proj_man.project', verbose_name='Проект'),
        ),
    ]
