# Generated by Django 4.0.8 on 2022-10-13 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proj_man', '0011_project_photo_alter_tasks_author_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSelfCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Наименование')),
                ('task', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='proj_man.tasks', verbose_name='Задача')),
            ],
            options={
                'verbose_name': 'Пользовательская категория',
                'verbose_name_plural': 'Пользовательская категория',
                'ordering': ['-pk'],
            },
        ),
    ]
