# Generated by Django 4.0.8 on 2022-10-13 13:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proj_man', '0013_userselfcategory_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSelfCategoryDictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Наименование')),
                ('html_color', models.CharField(blank=True, max_length=100, verbose_name='Цвет')),
            ],
            options={
                'verbose_name': 'Пользовательская категория справочник',
                'verbose_name_plural': 'Пользовательская категория справочник',
                'ordering': ['-pk'],
            },
        ),
        migrations.RemoveField(
            model_name='userselfcategory',
            name='title',
        ),
        migrations.AlterField(
            model_name='userselfcategory',
            name='task',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_self_category_task', to='proj_man.tasks', verbose_name='Задача'),
        ),
        migrations.AlterField(
            model_name='userselfcategory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_self_category', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='userselfcategory',
            name='category',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_self_category', to='proj_man.userselfcategorydictionary', verbose_name='Категория'),
            preserve_default=False,
        ),
    ]
