# Generated by Django 4.0.8 on 2022-10-13 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj_man', '0016_alter_userselfcategory_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userselfcategory',
            name='category',
            field=models.CharField(blank=True, max_length=100, verbose_name='Категория'),
        ),
    ]
