# Generated by Django 4.0.8 on 2022-10-13 16:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proj_man', '0019_remove_userselfcategory_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userselfcategorydictionary',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_self_category_dictionary', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.CreateModel(
            name='UserSelfSavedTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('save_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания задачи')),
                ('task', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_self_saved_task', to='proj_man.tasks', verbose_name='Задача')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_self_pk_saved_task', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Сохраненные записи',
                'verbose_name_plural': 'Сохраненные записи',
                'ordering': ['pk'],
            },
        ),
    ]
