# Generated by Django 4.0.8 on 2022-10-13 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proj_man', '0020_alter_userselfcategorydictionary_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userselfcategory',
            name='category',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_self_category', to='proj_man.userselfcategorydictionary', verbose_name='Категория'),
        ),
    ]
