# Generated by Django 4.0.8 on 2022-10-20 10:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proj_man', '0021_alter_userselfcategory_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskChangeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата изменения задачи')),
                ('column', models.CharField(blank=True, max_length=100, verbose_name='Строка изменения')),
                ('first_value', models.CharField(max_length=200, verbose_name='Первоначальное значение')),
                ('finish_value', models.CharField(max_length=200, verbose_name='Конечное значение')),
                ('task', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_change', to='proj_man.tasks', verbose_name='Задача')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_change_task', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'История изменения задачи',
                'verbose_name_plural': 'История изменения задачи',
                'ordering': ['pk'],
            },
        ),
    ]
