# Generated by Django 4.0.8 on 2022-10-20 11:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proj_man', '0022_taskchangehistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskChangeHistoryAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата изменения задачи')),
                ('task', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_change_action', to='proj_man.tasks', verbose_name='Задача')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_change_task_action', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Сведения о изменении задачи',
                'verbose_name_plural': 'Сведения о изменении задачи',
                'ordering': ['pk'],
            },
        ),
    ]
