# Generated by Django 4.0.8 on 2022-10-21 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proj_man', '0024_alter_taskchangehistoryaction_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskchangehistory',
            name='finish_value',
            field=models.CharField(blank=True, max_length=200, verbose_name='Конечное значение'),
        ),
        migrations.AlterField(
            model_name='taskchangehistory',
            name='first_value',
            field=models.CharField(blank=True, max_length=200, verbose_name='Первоначальное значение'),
        ),
        migrations.AlterField(
            model_name='taskchangehistoryaction',
            name='task',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='change_action_task', to='proj_man.tasks', verbose_name='Задача'),
        ),
    ]
