# Generated by Django 4.0.8 on 2022-10-21 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj_man', '0026_alter_taskchangehistory_finish_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskchangehistory',
            name='finish_value',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Конечное значение'),
        ),
        migrations.AlterField(
            model_name='taskchangehistory',
            name='first_value',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Первоначальное значение'),
        ),
    ]
