# Generated by Django 4.0.8 on 2022-10-21 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj_man', '0027_alter_taskchangehistory_finish_value_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskApproveStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_status', models.IntegerField(blank=True, default=0, null=True, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Название статуса')),
                ('description', models.CharField(blank=True, max_length=100, verbose_name='Описание статуса')),
            ],
            options={
                'verbose_name': 'Статус исполенности задачи',
                'verbose_name_plural': 'Статус исполенности задачи',
                'ordering': ['pk'],
            },
        ),
    ]
