# Generated by Django 4.0.8 on 2022-10-21 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proj_man', '0028_taskapprovestatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskApproveStatusActions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('approve_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proj_man.taskapprovestatus', verbose_name='Статус исполненности задачи')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proj_man.tasks', verbose_name='Задача')),
            ],
            options={
                'verbose_name': 'Текущий статус исполненности задачи',
                'verbose_name_plural': 'Текущий статус исполненности задачи',
                'ordering': ['pk'],
            },
        ),
    ]
