# Generated by Django 4.0.8 on 2022-10-21 17:46

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proj_man', '0029_taskapprovestatusactions'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskAnswerByExecutors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата ответа')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='task_answer_author', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('task', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='task_answer', to='proj_man.tasks', verbose_name='Задача')),
            ],
            options={
                'verbose_name': 'Ответ исполнителя',
                'verbose_name_plural': 'Ответ исполнителя',
                'ordering': ['pk'],
            },
        ),
    ]
