# Generated by Django 4.0.8 on 2022-10-21 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj_man', '0030_taskanswerbyexecutors'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskanswerbyexecutors',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
    ]
