# Generated by Django 4.0.8 on 2022-10-23 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proj_man', '0032_taskanswerbyexecutors_approve_action'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskanswerbyexecutors',
            old_name='description',
            new_name='answer_description',
        ),
    ]
