# Generated by Django 4.0.8 on 2022-10-27 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj_man', '0034_alter_taskanswerbyexecutors_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='bdate',
            field=models.DateField(blank=True, null=True, verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='project',
            name='edate',
            field=models.DateField(blank=True, null=True, verbose_name='Дата завершения'),
        ),
        migrations.AlterField(
            model_name='project',
            name='priority_tasks',
            field=models.ManyToManyField(blank=True, related_name='priority_tasks', to='proj_man.priority', verbose_name='Приоритеты для задач'),
        ),
    ]
