# Generated by Django 4.0.8 on 2022-11-04 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile_add', '0018_department_company_jobtitle_company'),
        ('proj_man', '0037_taskapprovestatusactions_user_sent_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='project_company', to='profile_add.company', verbose_name='Компания'),
        ),
    ]
