# Generated by Django 4.1 on 2022-09-29 19:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=30)),
                ('description', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Honor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='JobTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fathers_name', models.CharField(blank=True, max_length=30, verbose_name='Отчество')),
                ('person_id', models.CharField(blank=True, default=0, max_length=30, verbose_name='ИИН')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рожения')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Приступил к работе')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', verbose_name='Изображение')),
                ('education', models.CharField(blank=True, max_length=100, verbose_name='Образование')),
                ('location', models.CharField(blank=True, max_length=30, verbose_name='Место работы')),
                ('telephone', models.CharField(blank=True, max_length=30, verbose_name='Контактный телефон')),
                ('telephone_job', models.CharField(blank=True, max_length=30, verbose_name='Рабочий телефон')),
                ('skype', models.CharField(blank=True, max_length=30, verbose_name='Skype')),
                ('instagram', models.CharField(blank=True, max_length=30, verbose_name='Instagram')),
                ('linkedin', models.CharField(blank=True, max_length=30, verbose_name='LinkedIn')),
                ('facebook', models.CharField(blank=True, max_length=30, verbose_name='Facebook')),
                ('bio', models.TextField(blank=True, max_length=500, verbose_name='Биография')),
                ('website', models.CharField(blank=True, max_length=30, verbose_name='Веб-сайт')),
                ('quote', models.TextField(blank=True, max_length=500, verbose_name='Цитата для блога')),
                ('certificate', models.ManyToManyField(blank=True, related_name='sertificate', to='profile_add.certificate', verbose_name='Сертификат')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='company', to='profile_add.company', verbose_name='Компания')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='department', to='profile_add.department', verbose_name='Департамент')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gender', to='profile_add.gender', verbose_name='Пол')),
                ('honor', models.ManyToManyField(blank=True, related_name='honor', to='profile_add.honor', verbose_name='Звания в компании')),
                ('job_title', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobtitle', to='profile_add.jobtitle', verbose_name='Должность')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='education', to='profile_add.status', verbose_name='Статус')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
