# Generated by Django 4.1 on 2022-09-29 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_add', '0002_alter_certificate_options_alter_company_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='priority',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
