# Generated by Django 4.1 on 2022-10-02 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile_add', '0003_department_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='company', to='profile_add.company', verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='department', to='profile_add.department', verbose_name='Департамент'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gender', to='profile_add.gender', verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='job_title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jobtitle', to='profile_add.jobtitle', verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='education', to='profile_add.status', verbose_name='Статус'),
        ),
    ]
