# Generated by Django 4.1 on 2022-10-02 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_add', '0004_alter_profile_company_alter_profile_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='color',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
