# Generated by Django 4.0.8 on 2022-10-10 16:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profile_add', '0005_status_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='StartDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('start_time', models.TimeField(verbose_name='Время начала дня')),
                ('end_time', models.TimeField(verbose_name='Время завершение дня')),
                ('is_working', models.BooleanField(default=False, verbose_name='Работает')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Рабочий день',
                'verbose_name_plural': 'Рабочий день',
                'ordering': ['-pk'],
            },
        ),
    ]
