# Generated by Django 4.0.8 on 2022-10-10 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_add', '0007_alter_startday_end_time_alter_startday_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startday',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время завершение дня'),
        ),
        migrations.AlterField(
            model_name='startday',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время начала дня'),
        ),
    ]
