# Generated by Django 4.0.8 on 2022-10-11 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_add', '0008_alter_startday_end_time_alter_startday_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='startday',
            name='is_ended',
            field=models.BooleanField(default=False, verbose_name='Завершен'),
        ),
    ]
