# Generated by Django 4.0.8 on 2022-10-11 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_add', '0011_alter_startday_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeTrackingProperties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Время по регламенту')),
                ('start_day_time', models.TimeField(blank=True, null=True, verbose_name='Время начала дня по регламенту')),
                ('end_day_time', models.TimeField(blank=True, null=True, verbose_name='Время завершения дня по регламенту')),
                ('start_break_time', models.TimeField(blank=True, null=True, verbose_name='Время начала перерыва')),
                ('end_break_time', models.TimeField(blank=True, null=True, verbose_name='Время завершения перерыва')),
                ('company', models.IntegerField(blank=True, default=0, verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Время по регламенту',
                'verbose_name_plural': 'Время по регламенту',
            },
        ),
    ]
