# Generated by Django 4.0.8 on 2022-11-04 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_add', '0016_alter_startday_end_time_alter_startday_start_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobtitle',
            name='priority_number',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
