# Generated by Django 4.0.8 on 2022-11-04 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile_add', '0017_jobtitle_priority_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='department_company', to='profile_add.company', verbose_name='Компания'),
        ),
        migrations.AddField(
            model_name='jobtitle',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jobtitle_company', to='profile_add.company', verbose_name='Компания'),
        ),
    ]
