# Generated by Django 4.0.8 on 2023-01-23 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_add', '0018_department_company_jobtitle_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='JustTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Время по регламенту')),
                ('type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Время по регламенту')),
            ],
        ),
    ]
