# Generated by Django 4.1 on 2022-09-29 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common_settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('content_style', models.CharField(max_length=100, verbose_name='Стиль')),
                ('photo', models.ImageField(blank=True, upload_to='design/%Y/%m/%d', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Контент',
                'verbose_name_plural': 'Контент',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='HeaderType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('header_style', models.CharField(max_length=100, verbose_name='Стиль')),
                ('photo', models.ImageField(blank=True, upload_to='design/%Y/%m/%d', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Шапка',
                'verbose_name_plural': 'Шапка',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='SidebarType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('sidebar_style', models.CharField(max_length=100, verbose_name='Стиль')),
                ('photo', models.ImageField(blank=True, upload_to='design/%Y/%m/%d', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Боковая панель',
                'verbose_name_plural': 'Боковая панель',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='TemplateType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('template_style', models.CharField(max_length=100, verbose_name='Стиль')),
                ('photo', models.ImageField(blank=True, upload_to='design/%Y/%m/%d', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Интерфейс',
                'verbose_name_plural': 'Интерфейс',
                'ordering': ['-pk'],
            },
        ),
        migrations.AlterField(
            model_name='usertemplate',
            name='content_type',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='common_settings.contenttype', verbose_name='Тип контента'),
        ),
        migrations.AlterField(
            model_name='usertemplate',
            name='header',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='common_settings.headertype', verbose_name='Шапка'),
        ),
        migrations.AlterField(
            model_name='usertemplate',
            name='sidebar',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='common_settings.sidebartype', verbose_name='Боковая панель'),
        ),
        migrations.AlterField(
            model_name='usertemplate',
            name='template_type',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='common_settings.templatetype', verbose_name='Общий дизайн'),
        ),
    ]
