# Generated by Django 4.1 on 2022-09-29 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common_settings', '0002_contenttype_headertype_sidebartype_templatetype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IsSidebar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('is_sidebar', models.CharField(max_length=100, verbose_name='Стиль')),
                ('photo', models.ImageField(blank=True, upload_to='design/%Y/%m/d', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Наличие бокового меню',
                'verbose_name_plural': 'Наличие бокового меню',
                'ordering': ['-pk'],
            },
        ),
        migrations.AlterModelOptions(
            name='usertemplate',
            options={'ordering': ['-created_at'], 'verbose_name': 'Общий дизайн', 'verbose_name_plural': 'Общий дизайн'},
        ),
        migrations.AddField(
            model_name='usertemplate',
            name='is_sidebar',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.PROTECT, to='common_settings.issidebar', verbose_name='Наличие бокового меню'),
            preserve_default=False,
        ),
    ]
