# Generated by Django 4.1 on 2022-09-29 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_settings', '0003_issidebar_alter_usertemplate_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issidebar',
            name='is_sidebar',
            field=models.CharField(blank=True, max_length=100, verbose_name='Стиль'),
        ),
    ]
