# Generated by Django 4.0.8 on 2022-10-07 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_settings', '0007_alter_usertemplate_logo_dark_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertemplate',
            name='background_theme',
            field=models.ImageField(blank=True, upload_to='img/common/%Y/%m/%d', verbose_name='Изображение на фон'),
        ),
    ]
