# Generated by Django 4.1 on 2022-09-30 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menutree',
            name='icon',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='menutree',
            name='url',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
